export const data = [
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/500/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
];
