module.exports = [
  {
    id: '001',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/500/300',
  },
  {
    id: '002',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '003',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '004',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '005',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '006',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '007',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '008',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '009',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '010',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '011',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '012',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '北京市纪委监委通报：3 人被查！',
    commentsCount: 12,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
];
