module.exports = [
  {
    id: '001',
    title: '新疆巴州尉犁县：胡杨染金秋 大漠醉远客',
    newsFrom: 'CCTV',
    commentsCount: 12,
    comments: [
      {
        avator: 'https://picsum.photos/seed/picsum/30/30',
        name: 'test',
        date: '4 小时前',
        replys: [
          {
            avator: 'https://picsum.photos/seed/picsum/30/30',
            name: 'test',
            liked: false,
            likeCount: 12,
            date: '1 小时前',
          },
        ],
        liked: false,
        likeCount: 12,
      },
    ],
    likeCount: 7,
    liked: false,
    date: '5 小时前',
    image: 'https://picsum.photos/500/300',
    articleContent:
      '<p><strong>【文化中国行】</strong></p><p>光明日报记者 赵明昊 靳昊 孙金行 光明日报通讯员 宋唯一</p><p>秋日塞上的每一个角落，都在上演着色彩斑斓的童话。新疆巴音郭楞蒙古自治州尉犁县，在这片古老的土地上，独有的风情画卷静待每一位旅者的探寻。</p><p>尉犁县罗布人村寨的烤鱼美食。宋唯一摄</p><p>走进罗布人村寨，一种陌生、神秘而又迷人的气息扑面而来。无垠的沙海，清脆的驼铃声回荡耳际；静静流淌的塔里木河，宛如生命的脉搏；那一片片璀璨的胡杨林，金黄与火红交织，让这片土地既显苍茫又不失热烈。</p><p>村子里，许多高龄老人依旧耳聪目明，豁达豪放，和着古老的旋律翩然而舞。“我从塔里木河走来，牛羊遍地，鱼儿欢畅，姑娘，我多想到你的身旁……”古老的罗布淖尔民歌传唱至今。今天的罗布人村寨，据传是从罗布泊迁徙而来。村寨内的特色婚房前，来自五湖四海的游客身着民族服饰，在迎亲、跨火盆等热闹喜庆的仪式中，沉浸式感受当地的传统婚俗。</p><p>穿过罗布人村寨的广场，眼前是1.5亿年的胡杨树化石。胡杨树被维吾尔族称为“最美丽的树”，更是生命的象征。</p><p>站在高处放眼望去，大片的胡杨林仿佛被温柔的霞光所笼罩，明黄色的胡杨叶如同满天繁星，在水面上轻轻摇曳。走进胡杨林深处，可见汉唐烽燧、太阳墓、祭台，每一处文化遗存都透着原始与神秘，仿佛将一个个古老的传说向人娓娓道来。</p><p>“快看，骆驼旁边还有冲沙的越野车，看起来好刺激！”许多游客的目光被越野车冲沙所吸引。越野挑战赛、沙漠寻宝、民族特色烧烤美食节、民俗竞技赛等丰富多彩的趣味活动，提高了景区旅游品质。</p><p>游客在尉犁县罗布人村寨体验沙漠越野。汪志鹏摄</p><p>“搭建‘大漠戈壁’和‘金山银山’之间的桥梁，深入挖掘沙漠文化旅游潜力，让沙漠文化旅游产业逐渐成为我们旅游发展的‘新蓝海’。”尉犁县文旅局党组书记、副局长刘焱说，尉犁正努力把流量变为“留量”，让更多“头回客”成为“回头客”。</p><p>迷人的不只是罗布人村寨。在尉犁，险峻的罗布泊大裂谷、浩瀚的罗布淖尔国家湿地公园、优美的塔塔秘境……每一处都是自然与人文交织的奇迹。</p><p>在神秘的罗布泊深处，大裂谷两侧的峭壁高耸入云，如刀削斧劈般笔直陡峭。阳光洒在石壁上，古老的岩石诉说着岁月的沧桑。</p><p>罗布淖尔国家湿地公园里，水天一色的画卷令人沉醉。茂密的芦苇随风摇曳，优雅的白鹭翩翩起舞，灵动的翠鸟一闪而过，为这片宁静之地增添了无限生机。</p><p>光着脚丫行走在塔克拉玛干沙漠，细沙在脚趾缝里流溢着温暖与舒适。沙梁如刃，绵延远去，又似佳人侧卧的倩影……大漠，胡杨，碧水，蓝天，还有当地人们那份坚韧不拔、乐观向上的生活态度，无不让游客心驰神往。</p><p>尉犁县罗布淖尔国家湿地公园的胡杨林景色。汪志鹏摄</p><p>尉犁县罗布人村寨传统婚礼表演。丰盼摄</p><p>游客在尉犁县葫芦岛乘坐游船观赏秋景。韩峻摄</p><p>《光明日报》（2024年10月27日 10版）</p><p>来源： 光明网-《光明日报》</p>',
  },
  {
    id: '002',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300',
    ],
  },
  {
    id: '003',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '004',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '005',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '006',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '007',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '008',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: 'CCTV',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '009',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '新华社',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '010',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '新华社',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '011',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '新华社',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: '012',
    title: '北京市纪委监委通报：3 人被查！',
    newsFrom: '新华社',
    commentsCount: 12,
    likeCount: 7,
    date: '5 小时前',
    image: 'https://picsum.photos/200/300',
  },
];
